/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.winesync

import kotlin.test.Test
import kotlin.test.assertNotNull

class WineSyncTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = WineSync()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
